import React from 'react';
import { Box, Typography, Card, CardContent } from '@mui/material';

const ViewReports = () => {
  return (
    <Box>
      <Typography variant="h4" gutterBottom>
        View Credit Reports
      </Typography>
      
      <Card sx={{ mt: 3, boxShadow: 3, borderRadius: 2 }}>
        <CardContent>
          <Typography variant="h6" gutterBottom>
            Credit Reports Archive
          </Typography>
          <Typography variant="body1" paragraph>
            This section will display all credit reports generated by the franchise partner.
          </Typography>
          <Typography variant="body1" paragraph>
            Features to implement:
          </Typography>
          <ul>
            <li>
              <Typography variant="body2">
                Search and filter reports
              </Typography>
            </li>
            <li>
              <Typography variant="body2">
                Download reports in PDF format
              </Typography>
            </li>
            <li>
              <Typography variant="body2">
                Report details view
              </Typography>
            </li>
            <li>
              <Typography variant="body2">
                Export functionality
              </Typography>
            </li>
          </ul>
        </CardContent>
      </Card>
    </Box>
  );
};

export default ViewReports;